lib/apipie/application.rb
lib/apipie/static_dispatcher.rb

There was a chance that the registration of the StaticDispatcher was called
after the middleware stack was already initialized. Also not using the
Apipie.configuration at that point, as the rails initializer setting the
configuration might not be run yet by that time.

Fix ordering of registering the StaticDispatcher middleware

---

app/controllers/apipie/apipies_controller.rb
lib/apipie/application.rb

If not eager loaded, we need to load controllers otherwise no documentation will be generated/displayed.
The logic of reloaded (when already loaded) is moved to the `reload_documentation` method.

Load controllers if not eager loaded

---

lib/apipie/extractor/recorder.rb

It would seem that a PATCH request should behave like a PUT and POST in how the parameters get mapped.  I think typically, since you could be patching a large enough data set, the parameters wouldn't go in the URL but would be submitted as part of the request body.  Rails form builders treat PATCH as a POST with a hidden parameter.

Add PATCH to the POST, PUT list

---

lib/generators/apipie/install/templates/initializer.rb.erb

Added a recursive glob to the default configuration to prevent the need to specify these things, and put the base url in for a more accurate result.

Recursive globbing for controllers

---

lib/apipie/application.rb
spec/dummy/config/routes.rb

After upgrading to Rails 4.2.0, I began receiving a `SystemStackError` when Rails boots. After quite a bit of debugging, I traced it to the fact that I am using the `api!` method in my controllers to auto-detect the route for a given description. After more debugging, I traced it to the fact that I have several "catchall" redirects in my `routes.rb` file.
Apparently when the method `Apipie::Application#route_app_controller` attempts to recursively figure out the controller for a given app, the app generated from `redirect` satisfies none of the conditions and it will recurse until Ruby stops it.
I'm not sure of the exact fix, someone with more domain knowledge will have to say whether my patch is right or not. I was able to cause the problem under Rails 4.2 by adding the redirect route; I …

Avoid infinite recursion when there is a redirect

---

app/views/apipie/apipies/_headers.html.erb
app/views/apipie/apipies/_method_detail.erb
app/views/apipie/apipies/resource.html.erb
config/locales/en.yml
lib/apipie/dsl_definition.rb
lib/apipie/method_description.rb
lib/apipie/resource_description.rb
spec/controllers/users_controller_spec.rb
spec/dummy/app/controllers/users_controller.rb

To be honest, I couldn't find the tests for views, so I've added tests only for model part. I will add missing tests as soon as somebody tells me where they are :smile:

Add support for defining headers for API methods.

---

app/helpers/apipie_helper.rb

Started getting the following exception after bumping from 0.3.3 to 0.3.4:
```
ActionView::Template::Error:
undefined method `content_tag' for #<Apipie::ApipiesController:0x007ffdb1a5e608>
```

fix undefined method `content_tag`

---

README.rst
app/helpers/apipie_helper.rb
app/views/apipie/apipies/index.html.erb
app/views/apipie/apipies/plain.html.erb
app/views/apipie/apipies/resource.html.erb
app/views/apipie/apipies/static.html.erb
lib/apipie/dsl_definition.rb
lib/apipie/method_description.rb
spec/controllers/users_controller_spec.rb
spec/dummy/app/controllers/users_controller.rb

Reasons for feature and a description of the functionality described in issue https://github.com/Apipie/apipie-rails/issues/355
Example:
```
api :GET, '/users/see_another', 'Boring hidden method that we do not want clients to know about yet'
show false
see 'development#users#create'
see 'development#users#index', "very interesting method reference"
desc 'This method is boring, look at users#create.  It is hidden from documentation.'
def see_another
render :text => 'This is very similar to create action'
end
```

Hide controller methods from documentation

---

README.rst
config/locales/zh-CN.yml
config/locales/zh-TW.yml

Add explanation for `config.cache_dir`. Add locale `zh-CN` `zh-TW`

Add explanation for config cache_dir. / Add locale zh-CN zh-TW.

---

README.rst

The absence of dollar signs will make it possible to copy, paste and execute all three commands at once.

Make it easier to install apipie-rails

---

lib/apipie/param_description.rb
spec/lib/param_description_spec.rb

Feature
======
In some use cases, we want a param to required depending of the action. we could use action aware params (see https://github.com/Apipie/apipie-rails#action-aware-params), but how to handle parameters optional on creation but required on update ?
A possible solution is to pass a list of actions for which to parameter is required (See examples below)
**Make a param required for all actions**
```ruby
param :name, String, required true
```
**Make a param required only for update action**
```ruby
param :name, String, required :update
```
**Make a param required only for update and create actions**
```ruby
param :name, String, required [:update, :create ]
```
*Note*
Beware that the required param may still be overridden by action aware param if specified

Add an alternative to action aware required param

---

app/views/layouts/apipie/apipie.html.erb

This pull changes the basic layout to a fluid one. This fixes a problem in 0.0.21 where the contents appear misplaced.

Use fluid layout

---

lib/apipie/extractor/collector.rb
lib/apipie/validator.rb

A boolean parameters can be configured with both :bool and :boolean options. A boolean parameter can be any of: 'true', 'false', '1', '0'

A boolean parameters can be configured with both :bool and :boolean

---

app/views/layouts/apipie/apipie.html.erb

Thanks for an awesome gem :+1: 
I just added a viewport meta tag to make the documentation easier to read on mobile devices.
Tested on Android chrome (and chrome/safari/firefox on desktop).
Thanks again :)

Add viewport meta tag.

---

README.rst
lib/apipie/dsl_definition.rb
lib/apipie/errors.rb
lib/apipie/validator.rb
spec/controllers/users_controller_spec.rb
spec/dummy/app/controllers/users_controller.rb

`ParamMissing` can take the entire `ParamDescription` object instead of just the name, allowing it to interrogate the object to produce a custom missing message instead of the boilerplate `"Missing parameter #{@param.name}"`. Support is for a basic string or function. 
A primary use case for this is when an API is returning an error message that a client can then surface directly to a user without having to maintain a mapping of parameter names to human readable names IE 
`Missing parameter user_id` to `A user must be supplied to complete this action.`. An additional benefit in allowing a `Proc` is that we can evaluate runtime conditions to create the message, thereby allowing internationalization and providing greater usefulness in the error message.
This would also address the feature …

Add custom message support for missing parameters 

---

app/views/apipie/apipies/_params.html.erb
lib/apipie/param_description.rb
spec/controllers/users_controller_spec.rb
spec/lib/param_description_spec.rb

This allows the user to outline some purely textual validation text for
inclusion into the api documentation. Useful when clarifying a minor
point of the "type" validator that doesn't warrant a custom validate.
For example, specifying that an +Integer+ parameter must be > 0.
This change also provides more visual weight to the
validator/validations section of the parameter documentation.

Supply :validations parameter for simple inclusion

---

Gemfile.rails42
lib/tasks/apipie.rake

Fixes #421 (Missing template ../../layouts/apipie/apipie ... error). Credits: @FooBarWidget's [comment](https://github.com/Apipie/apipie-rails/issues/421#issuecomment-177998315).

Fix layout path (Rails 4.2.5.1 compatibility)

---

lib/apipie/extractor/writer.rb

- Turns uploaded file parameters into strings to represent a file was uploaded in the writer code.
- Addresses issue #296

Fixed to_json encoding error that occurs with uploaded file parameters.

---

lib/apipie/validator.rb

If an resource enum parameter has values that end in whitespace or dot
it can be hard to tell with certainty from the generated
documentation. This is because values aren't quoted or otherwise
enclosed. This patch encloses them in CODE elements, which stand out
with clarity from surrounding text.
Before:
After:

Render enum param values as CODE

---

README.rst

I believe this is supposed to be the `String` object instead of `:String` symbol.
Attaching a screenshot with the error:

Fix typo in Action Aware Params section of readme

---

lib/tasks/apipie.rake

After upgrading to version 0.3.6 our own custom layout wasn't used. This fix makes `base_path` and  `layouts_path` behave the same way.
The regression was introduced in #425.

Allow layouts to be overridable. Fixes a regression introduced in #425.

---

lib/apipie/extractor/recorder.rb

Currently, if an example's response body contains any blank line, it
returns nil.  This changes the approach to check for blank or all
whitespace to just data.strip.blank?

Handle blank data when parsing a example's response

---

README.rst

Example of translate function for I18n at Readme contained some errors.
if `str = nil ` than `translation missing: en.no key`
if `str = ''`  than `I18n::ArgumentError: I18n::ArgumentError`raised.

fix https://github.com/Apipie/apipie-rails/issues/492

---

lib/apipie/apipie_module.rb
lib/apipie/application.rb

app_info wrapped `<p>` tag before translate.

fix https://github.com/Apipie/apipie-rails/issues/490

---

lib/apipie/application.rb

I changed my api_base_url from '/api' to '' and had document generation fail because only nil base_urls were allowed.  This relaxes that and allows a blank base_url.

Allow a blank, not just nil, base_url.

---

lib/apipie/extractor/recorder.rb

One of my API routes allows multiple objects to be deleted.  In routing, it
looks like this:
```ruby
resources :posts do
collection do
delete :destroy
end
end
```
The generated examples from tests did not include the parameters.  This patch
treats :DELETE like PUT/POST/PATCH and includes the parameters in the generated
examples.

Include delete request parmeters in generated documentation

---

.travis.yml
Gemfile
Gemfile.rails32
Gemfile.rails50
apipie-rails.gemspec
lib/apipie/application.rb
lib/apipie/param_description.rb
spec/controllers/apipies_controller_spec.rb
spec/controllers/concerns_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/dummy/config/environments/development.rb
spec/dummy/config/environments/production.rb
spec/dummy/config/environments/test.rb
spec/dummy/config/routes.rb
spec/spec_helper.rb

Fixes Issue #415
Fixes Issue #495
Fixes Issue #510
Related to PR #465 and #526
Kudos to @aminariana and @sblackstone

Hopefully the final fix for Rails 5 compatibility

---

apipie-rails.gemspec
lib/apipie-rails.rb

Ruby 1.9+ ships json in the standard library, so a dependency on the
gem isn't necessary. See also rails/rails@f3433f7c.

Remove json gem dependency

---

lib/apipie/extractor/writer.rb

Right now if you want to use some files from paperclip in your examples (from RSpec) you can receive error:
`'encode': "\x89" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)`
I fixed this bug. Also I added special method for files, so now I can use files in nested hash and this method will convert file data to "FILE CONTENT".

Added recursion for documentation, fixed bug in examples with paperclip

---

README.rst
lib/apipie/error_description.rb
lib/apipie/errors.rb
spec/controllers/users_controller_spec.rb
spec/dummy/app/controllers/users_controller.rb

Recognize Rack Symbols as Status Codes

---

lib/tasks/apipie.rake

Before this change apipie-rails required all views to be copied into the
application's view folder even when only one of the files contained some
modification. After this change it is possible to override just a single
view.

Fallback to apipie views when application override isn't present

---

README.rst
lib/apipie/dsl_definition.rb
lib/apipie/method_description.rb
lib/apipie/param_description.rb
lib/apipie/validator.rb
spec/controllers/extended_controller_spec.rb
spec/dummy/app/controllers/concerns/extending_concern.rb
spec/dummy/app/controllers/extended_controller.rb

Sometimes, it's needed to extend an existing controller method with additional
parameters (usually when extending exiting API from plugins/rails engines).
The concern can be also used for this purposed, using `update_api` method.
The params defined in this block are merged with the params of the original method
in the controller this concern is included to.
```ruby
module Concerns
module OauthConcern
extend Apipie::DSL::Concern
update_api(:create, :update) do
param :user, Hash do
param :oauth, String, :desc => 'oauth param'
end
end
end
end
```
The concern needs to be included to the controller after the methods are defined
(either at the end of the class, or by using `Controller.send(:include, Concerns::OauthConcern)`.

A way to extend an exiting API via concern

---

lib/apipie/extractor/recorder.rb

When recording an example of a controller that calls [`send_file`](http://api.rubyonrails.org/classes/ActionController/DataStreaming.html#method-i-send_file), I'm getting this exception because of the binary content:
```
Writing examples to a file
/home/vagrant/pricematch/admin/vendor/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/json.rb:34:in `encode': "\xEC" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
from /home/vagrant/pricematch/admin/vendor/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/json.rb:34:in `to_json'
from /home/vagrant/pricematch/admin/vendor/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
from …
```

Fix example recording when using send_file

---

lib/apipie/application.rb

The commit 69c5bdcf51cb0d6a73a6cbf75dc4f58097f1f7e0 introduced calling _superclass_ on strings due to the fact that @controller_versions is now holding only the controller name as a string instead of the controller class itself. Due to this situation the 0.5.3 release is broken for me.
```
/Users/fl/.rvm/gems/ruby-2.4.1/gems/apipie-rails-0.5.3/lib/apipie/application.rb:129:in `controller_versions': undefined method `superclass' for "V1::ApplicationController":String (NoMethodError)
from /Users/fl/.rvm/gems/ruby-2.4.1/gems/apipie-rails-0.5.3/lib/apipie/application.rb:388:in `version_prefix'
from /Users/fl/.rvm/gems/ruby-2.4.1/gems/apipie-rails-0.5.3/lib/apipie/application.rb:346:in `get_resource_name'
from /Users/fl/.rvm/gems/ruby-2.4.1/gems/apipie-rails-0.5.3/lib/apipie/application.rb:104: …
```

constantize controller class before calling superclass

---

README.rst
app/views/apipie/apipies/index.html.erb
app/views/apipie/apipies/resource.html.erb
lib/apipie/dsl_definition.rb
lib/apipie/method_description.rb
lib/apipie/resource_description.rb
spec/lib/method_description_spec.rb

Resources can now be marked as deprecated. 
This marking is also referenced at the method level, meaning that resources marked as
deprecated will have all their methods marked as such as well.
This commit also includes related updates to the views used for
generating documentation

Allow for resource-level deprecations

---

app/views/layouts/apipie/apipie.html.erb

When the translation is missing it is wrapped with
<span class="translation_missing"... by rails. HTML elements
are not allowed within the title tag.

Prevent missing translation span in title

---

lib/apipie/application.rb
lib/apipie/extractor.rb
lib/tasks/apipie.rake
spec/dummy/config/routes.rb

As mentioned in #551 apipie has a tendency to break if there are routes pointing to missing controllers.
This PR makes apipie skip these routes, thereby ignoring the missing controllers.

Replaced String#constantize with String#safe_constantize so apipie won't break on a missing constant

---

README.rst
apipie-rails.gemspec
app/controllers/apipie/apipies_controller.rb
lib/apipie-rails.rb
lib/apipie/apipie_module.rb
lib/apipie/application.rb
lib/apipie/configuration.rb
lib/apipie/swagger_generator.rb
lib/apipie/validator.rb
lib/tasks/apipie.rake
spec/controllers/apipies_controller_spec.rb
spec/dummy/app/controllers/users_controller.rb
spec/lib/rake_swagger_spec.rb
spec/lib/swagger/openapi_2_0_schema.json
spec/lib/swagger/rake_swagger_spec.rb

Hi,
I've added the capability to auto-generate static [Swagger](https://swagger.io/) definition files from the Apipie DSL.
The resulting Swagger ([OpenAPI 2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md)) compliant JSON file can then be used to auto-generate REST clients, imported into tools like Postman, and so forth.
Swagger generation is implemented by crawling through Apipie's resource_descriptions construct.
The DSL is slightly enhanced to allow indication of default values of optional parameters.
There are a few configuration options that can be used to change the overall structure of the generated swagger file, in order to support both in:formData and in:body REST request styles.
Looking forward to hear your thoughts.

Added Swagger generation

---

.travis.yml

Also, remove ruby 2.0 as that's already pretty old release.
Fixes #587

Enable tests for ruby 2.4.3

---

lib/apipie/application.rb

FIPS forbits using MD5 at system level, therefore we need to use
something else inside.

Use SHA1 instead of MD5 to enable using APIPIE at FIPS-enables systems

---

lib/apipie/swagger_generator.rb

Hi! Thank you for maintaining the greate gem.
When generating a static Swagger JSON, we are missing `description` parameter.
To pass apipie's description annotation to swagger's description key.

Swagger json includes apipie's description as swagger's description

---

README.rst
lib/apipie/configuration.rb
lib/apipie/extractor/writer.rb
spec/lib/extractor/writer_spec.rb

This PR adds the option (default: false) to compress recorded examples using `Zlib`.
This can be benefitial by keeping examples out of git diffs and in reducing their size for big test suits.

Gzip examples

---

lib/apipie/application.rb

The current implementation causes namespaced controllers to fail when using the `api!` dsl method. This is due to `route.defaults[:controller]` being `'api/resource'` which then when `Controller` is added and `camelize` called will result in `Api::Resourcecontroller` instead of `Api::ResourceController`. By appending controller using snake case first results in `_controller` being properly camelized.

Use underscore when appending `controller` to the default controller string

---

spec/lib/swagger/swagger_dsl_spec.rb
spec/spec_helper.rb

There seems to be some issue with ordering when testing the swagger
results.
Also remove debug prints.

Fix failing tests on Ruby 2.5

---

lib/apipie/validator.rb
spec/lib/validators/array_validator_spec.rb

I had a situation where I needed to pass an array of integers in the query string. 
I tried using `array_of: Integer` but this didn't work, because the values was passed in as an array of strings: `["1", "2"]` instead of `[1, 2]`. 
This PR fixes that by allowing ArrayValidator to use other validators to validate the elements of the parameter array. So I was able to use `array_of: :number`. It should work for other validators too because it looks them up with `BaseValidator.find`. 
I also added a spec.

Allow ArrayValidator to use other validators to validate array elements

---

lib/apipie/extractor.rb

fixes https://github.com/Apipie/apipie-rails/issues/622

Fixes #622 examples not being generated for Rails < 5.0.0.

---

README.rst
lib/apipie/method_description.rb
spec/dummy/app/controllers/tagged_cats_controller.rb
spec/dummy/app/controllers/tagged_dogs_controller.rb
spec/lib/swagger/swagger_dsl_spec.rb

The original feature release caused Apipie's swagger generator (`rake apipie:static_swagger_json`) to crash with this error:
```ruby
NoMethodError: undefined method `_tag_list_arg’ for nil:NilClass
```
Unless you happened to define a `resource_description` for the parent class of a controller. (It turns out the `parent` variable isn't always a resource-desc object.)
This makes sure `_tag_list_arg` is called on non-nil objects only. I marked this as a bugfix because the error message you get doesn't explain how to fix it, and we shouldn't have to define `resource_description` for the parent classes.
`0.5.11` should be marked as faulty. Sorry about that.

[Bugfix] Stop swagger generation from crashing (if a controller's parent doesn't define a resource_description block)

---

lib/apipie/extractor.rb

The `FunctionalTestRecording` module's version of `process()` was not being called when running tests, which meant `@collector` was never initialized and so examples were not written to the file.
To fix this, we need to prepend `FunctionalTestRecording` to `ActionController::TestCase::Behavior`, not `ActionController::TestCase`, for reasons which I honestly did not manage to determine. (You can follow some of my debug rambling in the original issue.)
I'm not actually clear if this fix is safe to merge as is; presumably the original version is there for a reason, I'd've expected the `prepend()` to apply to the subclass as well as the parent, and this may be more version-specific than I'm giving it credit for. My testing was all done against APIPie 0.5.13 and Rails 5.1.6 and Ruby 2.5.1 and …

Fixes #629

---

lib/apipie/dsl_definition.rb
lib/apipie/param_description.rb
spec/controllers/extended_controller_spec.rb
spec/dummy/app/controllers/extended_controller.rb
spec/lib/swagger/swagger_dsl_spec.rb

Before this patch, we only supported updating nested hashes. For example
param :user, Hash do
param :login, String
end
and
param :user, Hash do
param :oauth, String
end
has been merged properly. However when merging top-level params, such as
param :login, String
and
param :oauth, String
no changes were propagated.

Support for adding new params via `update_api`

---

lib/apipie/validator.rb
spec/lib/validator_spec.rb

This fixes an issue when a validator includes a & that needs to be escaped in HTML.

HTML escape validator values

---

lib/apipie/extractor/recorder.rb

This allows the parameters of a rack request to be the `null` JSON string, `"null"`, when running apipie-example-updating commands:
```shell
dude@machine:~$ APIPIE_RECORD=examples bundle exec rspec spec/requests
```
There are times when `parse_data(...)` can return `nil` (specifically, when evaluating `JSON.parse("null")`, the response is `nil`).
This fixes the following types of specs:
```ruby
let(:params) { nil }
delete :something, params.to_json
delete :something, "null"
```
When running these specs, Apipie will analyze the env:
```ruby
def analyse_env(env)
if data = parse_data(env["rack.input"].read) # JSON.parse("null") #=> nil
env["rack.input"].rewind
elsif form_hash = env["rack.request.form_hash"]
end
end
```
So far nothing bad happens, but then, to actually read the specs, …

[Bugfix] Allow the "null" JSON string to be used as a parameter in Apipie spec examples (`show_in_doc`)

---

lib/apipie/static_dispatcher.rb
spec/lib/file_handler_spec.rb

Hook for `ArgumentError: string contains null byte`.
Example:
```
GET https://example.com/foo/bar%00.jpg
Traceback:
ArgumentError: string contains null byte
1 File "/app/vendor/bundle/ruby/2.3.0/gems/apipie-rails-0.3.6/lib/apipie/static_dispatcher.rb" line 13 in join
2 File "/app/vendor/bundle/ruby/2.3.0/gems/apipie-rails-0.3.6/lib/apipie/static_dispatcher.rb" line 13 in match?
3 File "/app/vendor/bundle/ruby/2.3.0/gems/apipie-rails-0.3.6/lib/apipie/static_dispatcher.rb" line 59 in call
```

ArgumentError: string contains null byte

---

lib/tasks/apipie.rake

Hi.
I think it would be better to use configured `swagger_content_type_input` value as default value of `rake apipie:static_swagger_json` option.
Or at least I'd like to update README.md. What do you think?

Use configured value when swagger_content_type_input argument is not passed

---

README.rst

I think the documentation could be more clear that this param is required. Thanks peeps, love the software.

Added the required param to the docs

---

README.rst

The number validator was missing and the decimal and array validator descriptions were mixed up.

Update validators documentation

---

lib/apipie/application.rb

- Since Rails constant loading looks in Rails load paths, it's possible
for files outside of api_controllers_matcher to be loaded
- Files that do not define an expected constant will cause a NameError
to be raised.  This was most commonly encountered with files in the
concerns/ directory, which caused a NameError for a missing
"Concerns::<name>" constant.
This make use of ActiveSupport::Dependencies::Loadable#require_dependency
to explicitly load the file and its constants in a way that cooperates
with Rails constant loading and unloading.
https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#require-dependency
https://api.rubyonrails.org/classes/ActiveSupport/Dependencies/Loadable.html#method-i-require_dependency
Fixes #347.

Load file directly instead of using Rails constant loading to do so

---

lib/apipie/dsl_definition.rb
lib/apipie/method_description.rb
spec/controllers/extended_controller_spec.rb
spec/dummy/app/controllers/concerns/extending_concern.rb

`update_api` block allows to update method `params` only. This fix adds a possibility to use `meta` method inside of the block:
```ruby
update_api(:index) do
meta metadata: 'data'
end
```
Also, there is a place for allowing usage of other similar methods. Just use the following pattern:
```ruby
def _apipie_update_something(method_desc, dsl_data)
end
def apipie_update_methods(methods, *args, &block)
_apipie_update_params(method_desc, dsl_data)
_apipie_update_something(method_desc, dsl_data)
end
```

Allows update metadata for methods

---

lib/apipie/markup.rb

Lazyloads rdoc for the defualt `Apipie::Markup::RDoc` to prevent errors on
require: `cannot load such file -- rdoc (LoadError)`.
Resolves: #544

Optional rdoc dependency with lazyload

---

.travis.yml
Gemfile
Gemfile.rails61
lib/tasks/apipie.rake

It looks like the changes in https://github.com/rails/rails/pull/35093 broke the use of ActionView::Base.new which should make this library Rails 6.1 compatible.

Add Rails 6.1 support in doc generation

---

config/locales/pt-BR.yml

Correcting the word Parâmentros, the correct one in Brazilian Portuguese is Parâmetros

Alter word Parâmentros locale pt-BR

---

README.rst

When a vowel makes a consonant sound (like `y` or `w`) we write `a` instead of `an`
See https://english.stackexchange.com/questions/105116/is-it-a-user-or-an-user for more info

Change "an" to "a"

---

lib/apipie/extractor/recorder.rb

by being less explicit in the super call, ie using just super and not super().
Also, line up the parameter signature with rails 6.0+.
In particular this stack track:
```      wrong number of arguments (given 1, expected 0)
```
see here for details, if you care.
https://stackoverflow.com/questions/31816149/difference-between-calling-super-and-calling-super

ruby 3.0: fixes the dreaded 'wrong number of arguments (given 1, expected 0)' error.

---

app/controllers/apipie/apipies_controller.rb
spec/controllers/apipies_controller_spec.rb

The default configuration has `default_locale = 'en'` but `languages = []`, so the check below fails. There's probably a cleaner way, but this logic matches that in `lib/tasks/apipie.rake` that treats the total set of languages to be `languages + default_local`.
#565 is at least one of the bug reports related to this.

Fix 'Method foo.en not found for resource bar' errors with no languages set

---

lib/apipie/static_dispatcher.rb
spec/lib/file_handler_spec.rb

https://github.com/Apipie/apipie-rails/issues/736 ArgumentError (invalid byte sequence in UTF-8). Remove invalid characters when parsing the file handler path.

ArgumentError (invalid byte sequence in UTF-8) #736

---

lib/apipie/param_description.rb

Current code only checks when allow_blank is true, it doesn't check if allow_blank is false.
If an attribute allows String, but doesn't want to allow empty string, allow_blank doesn't work at all.

allow_blank does not work

---

lib/apipie/swagger_generator.rb
spec/dummy/app/controllers/users_controller.rb
spec/lib/swagger/rake_swagger_spec.rb

apipie now generates a valid swagger schema for param descriptions using the array validator `in` option
closes #731

Fix schema generation for param descriptions using the array validator in option

---

README.rst
lib/apipie/configuration.rb
lib/apipie/swagger_generator.rb

Generated Swagger documentation allows the API to specify what
authentication mechanisms are available and which are required.
This adds support (through configuration) for the API to include that
information in the generated swagger docs.
https://swagger.io/docs/specification/2-0/authentication/

Support defining security mechanisms for Swagger

---

lib/apipie/param_description.rb
spec/lib/param_description_spec.rb

Expand the logic around blank value checking.
If `@allow_blank` is false, make sure it's not a BooleanValidator before looking for `value.blank?` as `false` is a valid boolean response, but
```ruby
false.blank? # => true
```
Create a test to replicate what we are seeing in use, when passing the value of `false` to a `:boolean` parameter (as opposed to `"false"` which is parsed as a string)

Update boolean handling of false

---

README.rst
lib/apipie/configuration.rb
lib/apipie/dsl_definition.rb
spec/controllers/users_controller_spec.rb

Currently, `validate_key` can be used to check whether any API is getting any extra parameters. The default behavior of `validate_key` is to raise an error if any unwanted parameter is found.
However, in many scenarios, I'd like to just ignore those extra parameters (i.e. those parameters should get deleted from the params) such that my controller action finally gets exactly what is defined. 
Currently, in order to achieve this, we have to again define those parameters which are required by our API. For example. we would do something like `params.permit(..)`. However, it'll be really great if I don't have to re-define those parameters at two places. Instead, apipie itself just deletes or ignores the unwanted or extra parameters.
This pull request defines one more key called as …

Skip extra parameters while validating the keys.

---

config/locales/ko.yml

Fixes https://github.com/Apipie/apipie-rails/issues/755
It seems that since the Korean translations were added, the first key on the YAML file was `en`, which was recently causing the problem.

[Bugfix] API Docs were showing up in Korean by default

---

lib/apipie/extractor/recorder.rb

Fixes https://github.com/Apipie/apipie-rails/issues/753
Context: https://github.com/Apipie/apipie-rails/pull/716#discussion_r852005248

Fix ruby2_keywords-related warning

---

lib/apipie/dsl_definition.rb

The resource description is set before the controller versions are defined.
When the namespaced_resources option is enabled this will lead to incorrect resource naming.

fix: Controller resource set before version

---

README.rst
lib/apipie/param_description.rb
lib/apipie/validator.rb
spec/lib/param_description_spec.rb
spec/support/custom_bool_validator.rb

My app has a custom boolean validator that looks like this:
```ruby
class BoolValidator < Apipie::Validator::BaseValidator
def validate(value)
value.in?([true, false])
end
def self.build(param_description, argument, options, block)
new(param_description) if argument == :bool
end
def description
"Must be a boolean."
end
end
```
But, this validator is failing when a `false` value is passed via the API because `false.blank?` is true and `allow_blank: false` is the default behavior for field definitions. There is a hard-coded [carve-out for BooleanValidator](https://github.com/Apipie/apipie-rails/blob/master/lib/apipie/param_description.rb#L128) so that this does not occur, but there is no way to replicate the same behavior in custom validators.
This PR adds a method to `BaseValidator` called …

Allow custom validators to opt out of allow_blank behavior

---

README.rst

I had some difficulty getting this project running since there isn't a Gemfile in the project, and I didn't see any contributing instructions. This PR adds some simple instructions for getting the test suite running to the Readme.
I do wonder why the Gemfile was removed and if the proper solution would be to add it back to the project.

Add contributing instructions to readme

---

README.rst

The code block in the readme documenting the `ignore_allow_blank?` functionality for custom validators that was added in https://github.com/Apipie/apipie-rails/pull/762 was not displaying. This fixes the RST syntax issue so it displays.

Fix readme code block

---

README.rst

Otherwise, the generated docs.json outputs the field as a `string` and not a `number`

Adds expected_type to IntegerValidator example

---

lib/apipie/validator.rb

Generated docs.json outputs the field as a `string` and not a `number`

Add expected_type to DecimalValidator

---

spec/lib/extractor/writer_spec.rb
spec/lib/rake_spec.rb
spec/lib/swagger/rake_swagger_spec.rb

`spec/dummy/` is not version controlled. 
Using a not tracked folder will avoid test generated files being indexed by an IDE or git.
Changes the output folder to `spec/dummy/tmp/`

Change output folder to `spec/dummy/tmp/`

---

lib/apipie/resource_description.rb
spec/dummy/config/initializers/apipie.rb
spec/lib/rake_spec.rb

Similar to https://github.com/Apipie/apipie-rails/pull/804
`public/apipie-cache` is version controlled.
Using a not tracked folder will avoid test generated files being indexed by an IDE or git.
Uncomments and assigns a not version controlled directory to `config.cache_dir`

Create test cache files under a not version controlled directory

---

lib/apipie/error_description.rb
lib/apipie/method_description.rb
lib/apipie/resource_description.rb
lib/apipie/response_description.rb

Full description cannot be translated as key was converted to HTML before translation. I changed that in this PR.

Fix #446 Fixing full_description translation

---

lib/apipie/method_description.rb
lib/apipie/swagger_generator.rb

Some fields had not i18n applied for swagger. At least this happened to method full description and method return description.
I also needed to apply the markup fix as in #808.

swagger missing i18n

---

lib/apipie/markup.rb

Previously we were using a shared instance of Rdoc::Markup::ToHtml. This instance changes its internal state when processing markups, which could lead to issues when generating docs concurrently.

Make html markup thread safe

---

README.rst
lib/apipie/configuration.rb
lib/apipie/extractor/recorder.rb
spec/lib/configuration_spec.rb
spec/lib/extractor/recorder_spec.rb

Currently we use the `action` param from the `Request` object to identify the correct action  but there might some kind of logic, a method for example, that directs the request to a specific action. 
Make the action matching strategy configurable by introducing `Apipie.configuration.api_action_matcher` that accepts a callable object.
<ins>Example</ins>
```ruby
class SomeMatchingStrategy
self.call(controller)
#... Matching logic
end
end
Apipie.configuration.api_action_matcher = SomeMatchingStrategy
```

Allow action matcher strategy to be configured

---

spec/spec_helper.rb

Fixes `Lint/NonDeterministicRequireOrder` Rubocop violation

Fix Lint/NonDeterministicRequireOrder error

---

.github/workflows/rubocop.yml
apipie-rails.gemspec

We could avoid having Rubocop violations merged into master if we run Robocop during PR 
WDYT 🤔 ?
https://github.com/Apipie/apipie-rails/pull/825 & https://github.com/Apipie/apipie-rails/pull/827 will propably need to be merged first.

Run Rubocop when opening PR

---

.rubocop.yml
lib/apipie/errors.rb
spec/lib/apipie/no_documented_method_spec.rb
spec/lib/apipie/response_does_not_match_swagger_schema_spec.rb

It does not seem to make a lot of sense to be enforced anymore ([Standard](https://github.com/testdouble/standard#why-arent-frozen_string_literal-true-magic-comments-enforced) has a good explanation) and since it's not used in the gem's codebase I think it can be disabled.

Disables FrozenStringLiteralComment rule

---

lib/apipie/application.rb
lib/apipie/resource_description.rb
spec/lib/apipie/application_spec.rb
spec/lib/apipie/resource_description_spec.rb

Closes https://github.com/Apipie/apipie-rails/issues/455
- Updates `get_resource_name` to return a `-` seperated resource id. 
The expected behavior when `Apipie.configuration.namespaced_resources?` is true is for a nested resource like `V1::Users::TweetsController` to return `v1-users-tweets` however it was returning `v1userstweets`
-  Uses the above dash separated format to return a readable nested resource name. Example if id is `some-nested-resource` `#name` will return `Some::Nested::Resource` that is later used in views.

Separate nested resource name

---

lib/apipie/param_description.rb
spec/lib/apipie/param_description_spec.rb
spec/lib/apipie/param_group_spec.rb

When required was passed from validator options it was ignored 
Closes https://github.com/Apipie/apipie-rails/issues/709
By using the validator options into ParamDescription options

Take into account validator options for  ParamDescription `required`

---

app/controllers/apipie/apipies_controller.rb
lib/apipie/apipie_module.rb
lib/apipie/application.rb
lib/apipie/dsl_definition.rb
lib/apipie/extractor.rb
lib/apipie/extractor/collector.rb
lib/apipie/generator/swagger/resource_description_collection.rb
lib/apipie/resource_description.rb
lib/tasks/apipie.rake
spec/controllers/api/v2/nested/resources_controller_spec.rb
spec/lib/apipie/application_spec.rb
spec/lib/apipie/generator/swagger/method_description/api_schema_service_spec.rb
spec/lib/apipie/generator/swagger/resource_description_composite_spec.rb
spec/lib/apipie/generator/swagger/resource_descriptions_collection_spec.rb
spec/lib/apipie/generator/swagger/schema_spec.rb

Although the function is named `get_resource_name` in reality it's generating the ID that is used as an id of the resource description as well as in the URLs of apipie.
Ideally what name is displayed in docs should have nothing to do with the internals of Apipie.
It deprecates `.get_resource_name` in favor of `.get_resource_id` to avoid confusion with `ResourceDescription#name`

Replace `get_resource_name` with `get_resource_id`

---

config/locales/en.yml

Closes #867
It's currently being used in the [`_method_detail.erb`](https://github.com/Apipie/apipie-rails/blob/master/app/views/apipie/apipies/_method_detail.erb#L40) partial.

Add missing 'returns' translation

---

lib/apipie/extractor/recorder.rb

PDF responses return binary data that cannot be parsed correctly.

Skip parse body for pdf responses

---

lib/apipie/application.rb
spec/dummy/app/controllers/api/v2/architectures_controller.rb

This should be `get_resource_id`. The method `remove_method_description` was not exercised by the specs so it wasn't caught. (see #864)
This was causing apipie to crash during application boot.

Fix startup crash due to typo

---

lib/apipie/application.rb
spec/dummy/config/routes.rb

In large apps with many routes (1500+), using the `api!` method would be quite slow because `routes_for_action` looped over every route trying to constantize the controller name. Compound this by the number of times `api!` is used in the app.
Furthermore, each controller utilizing `api!` would constantize the next controller using `api!`, which would constantize the next controller and so on, recursively and potentially very deeply.
This change caches a hash of controller+action => routes using only the controller name, avoiding the time-consuming loops, constantization, and recursion.
As a bonus, the cache is cleared when documentation is reloaded, fixing a bug where new routes added while the app is running wouldn't get picked up.
On small apps with not too many routes, there isn't much …

Improve performance of route detection

---

.rubocop.yml
README.rst
lib/apipie/application.rb
lib/apipie/resource_description.rb
spec/controllers/api/v2/nested/resources_controller_spec.rb
spec/controllers/api/v2/sub/footguns_controller_spec.rb
spec/dummy/app/controllers/api/v2/base_controller.rb
spec/dummy/app/controllers/api/v2/empty_middle_controller.rb
spec/dummy/app/controllers/api/v2/nested/resources_controller.rb
spec/dummy/app/controllers/api/v2/sub/footguns_controller.rb

This is helpful if you have a very structured hierarchy of API controllers and would like to define the naming logic once in a base controller.
* Allow resource_name to be a string, symbol, or proc
* Search all the way up the controller hierarchy for a value
* Continue searching even if a particular controller doesn't have a `resource_description` block
Edit: I had to set Rubocop's target Ruby version to 2.6 in order to get a bunch of offenses to go away. I'm not sure why that suddenly started happening (my PR from last week didn't have any issues).

Allow resource_name to be inherited

---

app/controllers/apipie/apipies_controller.rb
spec/lib/apipie/apipies_controller_spec.rb

The path traversal sanitization was incorrectly filtering out paths that included the `-` character. Namespaced resources generates files like `api-v1-resource.html` which were then returning a 400.

Fix cache rendering with namespaced resources

---

lib/apipie/extractor/recorder.rb

DEPRECATION WARNING: Rails 6.1 will return Content-Type header without modification. If you want just the MIME type, please use `#media_type` instead. (called from analyze_functional_test at ~/apipie-rails/lib/apipie/extractor/recorder.rb:51)

Fix deprecated `content_type` on Rails >= 6

---

lib/apipie/extractor/collector.rb
spec/lib/apipie/extractor/collector_spec.rb

This should be `get_resource_id`. The method `ignore_call?` wasn't exercised by the specs so it wasn't caught. (see #864)
This was causing an exception when recording examples.

Fix typo in Collector

---

lib/apipie/application.rb
lib/apipie/resource_description.rb
spec/controllers/api/v2/empty_middle_controller_spec.rb
spec/dummy/app/controllers/api/v2/empty_middle_controller.rb

When using namespaced resources, climbing the controller hierarchy was broken in really specific circumstances.
Bug introduced in https://github.com/Apipie/apipie-rails/pull/872

Fix error climbing controller hierarchy

---

README.rst
lib/apipie/generator/swagger/config.rb
lib/apipie/generator/swagger/method_description/api_schema_service.rb
spec/lib/apipie/generator/swagger/method_description/api_schema_service_spec.rb

- This option allows the resource tags to be manually specified
- Fixes #759

Swagger: Adds option to skip default tags

---

.rubocop_todo.yml
lib/apipie/extractor/collector.rb
lib/apipie/extractor/recorder.rb
spec/lib/apipie/extractor/recorder_spec.rb

Copied the changes from #440 and added some specs for the changes

Improved support for multipart/form-data example recording

---

lib/apipie/generator/swagger/param_description/builder.rb
spec/lib/apipie/generator/swagger/method_description/response_schema_service_spec.rb
spec/lib/apipie/generator/swagger/param_description/builder_spec.rb
spec/lib/apipie/swagger_generator_spec.rb
spec/lib/swagger/openapi_2_0_schema.json

This PR should fix the #888 issue. I'm not sure how exactly the `in_schema` is used and whether we can just ignore it in `Apipie::Generator::Swagger::ParamDescription::Builder`. But since the `in_schema` is almost always `true`, I couldn't find a way how to combine it with the `param_description` in other way.

Fix Swagger warnings for properties

---

lib/apipie/generator/swagger/param_description/builder.rb
spec/lib/apipie/apipies_controller_spec.rb
spec/lib/apipie/generator/swagger/param_description/builder_spec.rb

When using `param` as:
```ruby
param(:name, String, required: false, default_value: nil)
```
there would be a warning that `default_value` is missing.
This fix changes from checking `options[key].blank?` to `options.key?(key)`.

param: Consider default_value: nil as valid config

---

README.rst
lib/apipie/generator/swagger/param_description/builder.rb
spec/dummy/app/controllers/pets_controller.rb
spec/lib/apipie/generator/swagger/method_description/response_schema_service_spec.rb
spec/lib/apipie/generator/swagger/param_description/builder_spec.rb
spec/lib/apipie/swagger_generator_spec.rb
spec/lib/swagger/rake_swagger_spec.rb

[WHY]
* The generated swagger JSON didn't include the example for the response. This will be useful when the user wants to know the response example, this will help them to understand the API quicker.
[HOW]
* add a new option for the params description `ex` to provide an example for the specific parameters
Here is a swagger editor preview with the ex option, which correctly shows the example in response:

support property example

---

lib/apipie/dsl_definition.rb
lib/apipie/errors.rb
lib/apipie/extractor/collector.rb
lib/apipie/extractor/recorder.rb
lib/apipie/extractor/writer.rb
lib/apipie/generator/swagger/config.rb
lib/apipie/generator/swagger/method_description/parameters_service.rb
lib/apipie/generator/swagger/param_description/type.rb
lib/tasks/apipie.rake
spec/lib/apipie/extractor_spec.rb
spec/lib/apipie/generator/swagger/param_description/type_spec.rb
spec/lib/swagger/rake_swagger_spec.rb

Closes https://github.com/Apipie/apipie-rails/issues/903

Use array items type from validator

---

.github/workflows/rubocop-challenger.yml
.github/workflows/rubocop.yml
spec/lib/apipie/generator/swagger/param_description/builder_spec.rb
spec/lib/swagger/swagger_dsl_spec.rb

Fix rubocop workflow and rubocop-challenger workflow.
-  `gemfiles/Gemfile.rails50` is missing.  see https://github.com/Apipie/apipie-rails/actions/runs/7762735936/job/21173684766
- set `RUBY_VERSION` env on rubocop and rubocop-challenger workflow because Ruby 3.2.3 released.
- Skipped [7bc8e18](https://github.com/Apipie/apipie-rails/pull/910/commits/7bc8e18a5ac03f1534368e86b0506ce567d60191) because the expected values for the tests have changed, causing the tests to fail.

Fix rubocop CI

---

apipie-rails.gemspec

This PR adds [metadata](https://guides.rubygems.org/specification-reference/#metadata) for [rubygems.org](https://rubygems.org/gems/apipie-rails) and use https url

Add metadata for rubygems.org and use https url

---

.github/workflows/build.yml
.github/workflows/rubocop-challenger.yml
.github/workflows/rubocop.yml

GitHub is [planning to upgrade to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Versions prior to actions/checkout v3 use an outdated version of node, so we will upgrade to actions/checkout v4, where [Node 20 is the default](https://github.com/actions/checkout/releases/tag/v4.0.0).

Bump actions/checkout

---

.github/workflows/build.yml
Gemfile

This Pull Request adds support for Ruby 3.4.0-preview1.  Running the current code with Ruby 3.4.0-preview1 results in the following error:
```sh
An error occurred while loading ./spec/lib/validators/array_validator_spec.rb. - Did you mean?
rspec ./spec/lib/apipie/validator_spec.rb
Failure/Error: require "action_controller/railtie"
LoadError:
cannot load such file -- bigdecimal
```
The reason for this error is that in Rails 7.0.X, bigdecimal is not added to the Gemfile (ref: [Rails PR #49039](https://github.com/rails/rails/pull/49039)). Therefore, for Ruby 3.4 and above, we need to use Rails 7.1.X for testing.

Support for Ruby 3.4.0-preview1

---

app/views/apipie/apipies/_params.html.erb
app/views/apipie/apipies/_params_plain.html.erb
config/locales/en.yml
config/locales/ko.yml

#925  
"allow_blank" setting is not displayed in api doc
i added blank allowed message

"allow_blank" setting is not displayed in api doc

---

README.md
app/views/apipie/apipies/_method_detail.erb
lib/apipie/generator/swagger/method_description/response_service.rb
lib/apipie/response_description.rb
spec/lib/apipie/generator/swagger/method_description/response_service_spec.rb
spec/lib/apipie/response_description/response_object_spec.rb
spec/lib/apipie/response_description_spec.rb

To define custom response headers https://github.com/Apipie/apipie-rails/issues/706
Extend the `Apipie::ResponseDescription::ResponseObject` with a header method
```ruby
api :GET, "/pets/:id/with-extra-details", "Get a detailed pet record"
returns code: 200, desc: "Detailed info about the pet" do
param_group :pet
property :num_legs, Integer, :desc => "How many legs the pet has"
header 'Link', String, 'Relative links'
header 'Current-Page', Integer, 'The current page', required: true
end
def show
render JSON({ :pet_name => "Barkie", :animal_type => "iguana", :legs => 4 })
end
```

Custom headers responses

---

lib/apipie/generator/swagger/param_description/builder.rb
lib/apipie/generator/swagger/param_description/type.rb
spec/lib/apipie/generator/swagger/param_description/builder_spec.rb
spec/lib/apipie/generator/swagger/param_description/type_spec.rb

Fix how we generate warnings about params or properties defined as Hashes without defining what keys they can have inside them.
Our swagger docs stopped working with an ArgumentError:
ArgumentError: wrong number of arguments (given 0, expected 1)
And it turns out it was in the `Apipie::Generator::Swagger::ParamDescription::Type#warn_hash_without_internal_typespec` method where we call `@controller_method.method` and `@controller_method` was a `Apipie::Generator::Swagger::MethodDescription::Decorator` instance instead of a `Apipie::MethodDescription` instance.  The `Decorator` is a `SimpleDelegator` onto a `MethodDescription` so it _should_ be able to call `method` with no arguments, but it turns out that `SimpleDelegator` won't delegate `method` because it keeps it to refer to …

Fix error for hash object warnings with delegated method descriptions

---

lib/tasks/apipie.rake

We tried to integrate this project this week but ran into a very specific issue. We have a field called `render_page` on one of our models. And we're using [factory_bot](https://github.com/thoughtbot/factory_bot) to build factories for our tests. Inside our factory we're calling a `render_page` function to set up the data for the initial value. (i.e.)
```ruby
FactoryBot.define do
factory :my_model do
render_page { "the_page" }
end
end
```
As soon as we add `apipie-rails` to the Gemfile like this it starts failing.
```
gem "apipie-rails"
```
Example output
```
NoMethodError: undefined method `namespace' for module Apipie (NoMethodError)
/Users/person/Source/project/packs/docs/config/initializers/apipie.rb:35:in `<module:Apipie>'
/Users/person/Source/project/packs/docs/config/initializers/ap …
```

Rename render_page in apipie.rake to render_apipie_page

---

spec/dummy/config/boot.rb

See https://stackoverflow.com/questions/79360526/uninitialized-constant-activesupportloggerthreadsafelevellogger-nameerror

Fix issue with loading Rails logger

---

.github/workflows/build.yml
lib/apipie/application.rb
lib/apipie/dsl_definition.rb
lib/apipie/extractor.rb
lib/apipie/param_description.rb
lib/apipie/response_description.rb
lib/apipie/static_dispatcher.rb
lib/apipie/validator.rb
spec/spec_helper.rb

20.04 is deprecated and will be removed soon

Update CI workflow to run on Ubuntu 24.04

---

lib/apipie/application.rb
lib/apipie/generator/swagger/config.rb

Fix deprecation method ActiveSupport::Deprecation.warn. Replaced with ActiveSupport::Deprecation.new.warn

Rails 72 fix deprecation warn
