README.rst

Went through the README and just cleared up some of the wording so it reads better.

Tidy up grammar, flow and some typos.

---

README.rst
lib/apipie/dsl_definition.rb
lib/apipie/method_description.rb
spec/controllers/concerns_controller_spec.rb
spec/dummy/app/controllers/concerns/sample_controller.rb

One can now use the concerns without any concerns about subscriptions.

Support the api! keyword from concerns.

---

config/locales/pt-BR.yml

Including brasilian portuguese internationalization and extra keys included in pull request: #341

Including brazilian portuguese internationalization

---

app/controllers/apipie/apipies_controller.rb

added heading helper_method to controller for when helper is not loaded

---

README.rst

Change old reference to foreman_api to apipie-bindings.

Change bindings project to apipie-bindings

---

app/views/apipie/apipies/_errors.html.erb
app/views/apipie/apipies/method.html.erb
app/views/apipie/apipies/resource.html.erb
app/views/apipie/apipies/static.html.erb
lib/apipie/error_description.rb

Changes design errors description, more friendly display

---

app/views/apipie/apipies/apipie_404.html.erb

Fix so that raw HTML renders as HTML.

Fix unwanted html encoding.

---

README.rst
app/controllers/apipie/apipies_controller.rb
lib/apipie/configuration.rb
spec/controllers/apipies_controller_spec.rb

This allows someone to configure custom authorization of controllers and methods.

Authorization of controllers and methods

---

config/locales/de.yml
config/locales/en.yml
config/locales/es.yml
config/locales/pl.yml
config/locales/ru.yml
config/locales/tr.yml

Two spaces per identation level are preferred in Ruby world.
It also updates `JavaScript` word in Polish translation.

Unify indentations across all locale files

---

Gemfile.rails40
Gemfile.rails41
Gemfile.rails42

fix mime-types < 3.0 for ruby version < 2.0

Fix travis build

---

README.rst

They're much crisper on high resolution displays. :-)

Replace PNG badges with SVG

---

config/locales/it.yml

I added the italian locale file

add IT locale

---

lib/apipie/application.rb

Fixes #539 
(regression in 0.5.0 on Rails 4)

Use AD::Reloader on Rails 4, app.reloader only on Rails 5+

---

app/controllers/apipie/apipies_controller.rb

prevent lang in url when config.translate is false

---

config/locales/fr.yml

Some traductions might prove a bit rough to understand or approximate. I am pretty confident it will do its job otherwise.

Added french locale

---

README.rst
lib/apipie/extractor/collector.rb
lib/apipie/validator.rb

Simple patch - allow number params to have decimal places.

new validator - DecimalValidator

---

lib/apipie/validator.rb
spec/lib/validator_spec.rb

Expect :number to have type 'numeric'

---

app/views/apipie/apipies/_method_detail.erb
app/views/apipie/apipies/_params.html.erb
config/locales/en.yml
lib/apipie/method_description.rb

fix returns displaying

---

app/controllers/apipie/apipies_controller.rb
lib/apipie/resource_description.rb

https://github.com/Apipie/apipie-rails/issues/654

Fix authorization of resources

---

.travis.yml
Gemfile.rails42
Gemfile.rails60

+ remove some older rails versions to reduce the test matrix.

Add rails6 matrix to jenkins

---

lib/apipie/swagger_generator.rb
spec/controllers/users_controller_spec.rb
spec/dummy/app/controllers/users_controller.rb

Resolves https://github.com/Apipie/apipie-rails/issues/670

Swagger export: Ability to include default values in headers

---

lib/tasks/apipie.rake

File.exists? is deprecated; use File.exist? instead

Fix depreciated File.exists.

---

lib/apipie/validator.rb

Fixes doc comment typo

---

apipie-rails.gemspec
gemfiles/Gemfile.rails42
gemfiles/Gemfile.rails42.lock
gemfiles/Gemfile.rails52
gemfiles/Gemfile.rails60
gemfiles/Gemfile.rails61
spec/dummy/config/application.rb
spec/dummy/config/environments/development.rb
spec/dummy/config/environments/production.rb
spec/dummy/config/environments/test.rb

Most of rails isn't required, and this gem should not bring all of it into minimalists apps, such as an API applications
includes #740

Only depends on railties and activemodel

---

config/locales/ko.yml

add `ko` locale

---

.github/workflows/build.yml
CHANGELOG.md
gemfiles/Gemfile.rails70
spec/dummy/app/controllers/concerns_controller.rb
spec/dummy/app/controllers/extending_concern.rb
spec/dummy/app/controllers/overridden_concerns_controller.rb
spec/dummy/app/controllers/sample_controller.rb
spec/dummy/config/application.rb

Rails 7 support

---

README.rst

I struggled for a little too long to figure out how to best catch with error from a param validation failure. It was causing my server to 500, even in production. Yuck city. Thought this example would be helpful. Thanks for the library!

Update readme with error handling example

---

Rakefile
apipie-rails.gemspec

- remove/clean up dev dependencies
- remove unused rake task

Review dependencies

---

lib/apipie/dsl_definition.rb

Fix tiny typo in docs

---

.vscode/settings.json
gemfiles/Gemfile.tools

In particular, if you're using Shopify's [ruby-lsp](https://github.com/Shopify/ruby-lsp) with the [VS Code extension](https://github.com/Shopify/vscode-ruby-lsp), this will enable format-on-save and showing offenses in your editor.

Add Gemfile.tools for IDE usage

---

README.md

Fixes: c5c08f518d6c ("Convert README from RTS to MD")

Fix the DecimalValidator header in README.md

---

README.md

Update link for rdoc in README
